### ISSUE TITLE
Providing 1.19.2 build

### ISSUE THREAD

**Issue by LupineWitch** [cubicoder/Well-Mod#1]
Could you provide a 1.19.2 build please?
I wish to include this in my game, but the rest of the mods I am using are on 1.19.2.

**Comment by cubicoder** [comment]
Thanks for asking! Normally I try to stick to the latest version, but it seems like a lot of mods stayed on 1.19.2 so I'll go ahead and release for that version too. I'll close this once I get it uploaded.

**Comment by cubicoder** [comment]
@LupineWitch All done! The mod is now available for 1.19.2 on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/just-a-well/files/4656937) and [Modrinth](https://modrinth.com/mod/just-a-well/version/RRpcxSiv), and under the [Releases](https://github.com/cubicoder/Well-Mod/releases) here.
